### ISSUE TITLE
Unable to disable Hermit Heads

### ISSUE THREAD

**Issue by rykea1** [MC-Machinations/VanillaTweaks#31] opened 2021-07-10 13:16 UTC
I'm unable to disable hermit heads from the wandering trader pack,
I've restarted the server after editing the config, as well as using the vt reload command & it is the same everytime I re summon the wandering trader.

**Comment by Machine-Maker** [comment] 2021-07-10 14:37
Yep, looks like I’m completely ignoring the config value. Thanks for the report.

**Comment by Machine-Maker** [comment] 2021-07-10 20:26
Actually I can't reproduce this. And looking at the code, it *is* looking at the configuration for it. You sure you dont have any datapacks or plugins that might also be adding this behavior?

**Comment by UnknownVariables-here** [comment] 2021-07-14 17:23
Same issue aswell no other datapacks

**Comment by Machine-Maker** [comment] 2021-07-14 17:47
@UnknownVariables-here I'm very confused about what you said here, there is no `has-player-heads` setting anywhere in VanillaTweaks

**Comment by teakivy** [comment] 2021-08-03 00:15
Hey @UnknownVariables-here & @rykea1 , I just read this (nearly a month later) I am indeed working on my own Vanilla Tweaks, and I believe this issue is for my version. [github.com/teakivy/vanilla-tweaks](https://github.com/teakivy/vanilla-tweaks) This will be fixed in the next version (v1.4.2-beta) if you are still watching this xD

**Closed** 2021-08-05 00:50 UTC
Labels: bug, question
